* pwntools intro
Pwntools is a python ctf library designed for rapid exploit development. It essentially help us write exploits quickly, and has a lot of useful functionality behind it.

Also one thing to note, pwntools has Python2 and Python3 versions. Atm this course uses the Python2, but I have plans to switch it all over to Python3. Just keep in mind that some things change between Python2 to the Python3 versions, however the changes are relatively small.

** Installation
It's fairly simple process. The installation process is pretty much just using pip:

#+begin_example
$    sudo pip install pwn
#+end_example

If you have any problems, google will help a lot.

** Using it
So this is going to be an explanation on how you do various things with pwntools. It will only cover a small bit of functionality.

If we want to import it into python:

#+begin_example
from pwn import *
#+end_example

Now one thing that pwntools does for us, is it has some nice piping functionality which helps with IO. If we want to connect to the server at =github.com= (if you have an IP address, just swap out the dns name with the IP address) on port =9000= via tcp:

#+begin_example
target = remote("github.com", 9000)
#+end_example

If you want to run a target binary:

#+begin_example
target = process("./challenge")
#+end_example

If you want to attach the =gdb= debugger to a process:

#+begin_example
gdb.attach(target)
#+end_example

If we want to attach the =gdb= debugger to a process, and also immediately pass a command to =gdb= to set a breakpoint at main:

#+begin_example
gdb.attach(target, gdbscript='b *main')
#+end_example

Now for actual I/O. If we want to send the variable =x= to the =target= (target can be something like a process, or remote connection established by pwntools):

#+begin_example
target.send(x)
#+end_example

If we wanted to send the variable =x= followed by a newline character appended to the end:

#+begin_example
target.sendline(x)
#+end_example

If we wanted to print a single line of text from =target=:

#+begin_example
print target.recvline()
#+end_example

If we wanted to print all text from =target= up to the string =out=:

#+begin_example
print target.recvuntil("out")
#+end_example

Now one more thing, ELFs store data via least endian, meaning that data is stored with the least significant byte first. In a few situations where we are scanning in an integer, we will need to take this into account. Luckily pwntools will take care of this for us.

To pack the integer =y= as a least endian QWORD (commonly used for =x64=):

#+begin_example
p64(x)
#+end_example

To pack the integer =y= as a least endian DWORD (commonly used for =x86=):

#+begin_example
p32(x)
#+end_example

It can also unpack values we get. Let's say we wanted to unpack a least endian QWORD and get it's integer value:

#+begin_example
u64(x)
#+end_example

To unpack a DWORD:

#+begin_example
u32(x)
#+end_example

Lastly if just wanted to interact directly with =target=:

#+begin_example
target.interactive()
#+end_example

This is only a small bit of the functionality pwntools has. You will see a lot more of the functionality later. If you want to see more of pwntools, it has some great docs: [[http://docs.pwntools.com/en/stable/]]
